name:    flow2dot
version: 0.9.1
license: BSD3
license-file: LICENSE
author: Dmitry Astapov <dastapov@gmail.com>
maintainer: Dmitry Astapov <dastapov@gmail.com>
synopsis: Library and binary to generate sequence/flow diagrams from plain text source
description: Generates sequence diagrams from textual descriptions with help of Graphviz graph drawing tool.
homepage: https://github.com/adept/flow2dot
category: Tool, Console
stability: stable

tested-with:        GHC ==6.10.4, GHC ==8.8.3
build-type:         Simple
extra-source-files:
  - README.md
  - ChangeLog.md
  - sample.flow
  - sample.png

dependencies:
  - base >=3 && <=5
  - mtl >= 1.0
  - containers
  - parsec
  - dotgen

library:
  source-dirs: .
  exposed-modules:
    - Text.FlowDiagram

executables:
  flow2dot:
    source-dirs: .
    main:       flow2dot.hs
    dependencies:
      - flow2dot

tests:
  flow2dot-test:
    source-dirs: test
    main: test.hs
    dependencies:
      - QuickCheck
      - flow2dot

github: adept/flow2dot
